@baseUrl = http://localhost:5001
@urlpath = api/v1

###
POST {{baseUrl}}/{{urlpath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
 "email": "johndoe@example.com",
 "adminFullName": "John Doe",
 "username": "johnd",
 "password": "SecurePass123!",
 "businessName": "Tech Innovations LLC",
 "businessType": "Retail",
 "businessCategory": "Technology"
}

###
POST {{baseUrl}}/{{urlpath}}/login
Content-Type: application/json
Accept: application/json
withCredentials: true

{
 "email": "johndoe@example.com",
 "password": "SecurePass123!",
 "username": "johnd"
}

###
GET {{baseUrl}}/{{urlpath}}/logout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlpath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true


###
POST {{baseUrl}}/{{urlpath}}/products
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "sku": "PRD12345",
    "productName": "Wireless Earbuds",
    "businessId": "675df7831e2e82150bc6c012",
    "longDescription": "High-quality wireless earbuds with noise cancellation and 20-hour battery life.",
    "shortDescription": "Wireless earbuds with long battery life.",
    "currency": "USD",
    "productCategory": "Electronics",
    "productType": "Physical",
    "barcode": "1234567890123",
    "basePrice": 50.0,
    "salePrice": 40.0,
    "discount": 20.0,
    "unit": "piece",
    "tags": ["wireless", "audio", "earbuds"],
    "isActive": true,
    "productImages":[{
        "url": "",
        "isPrimary": true
    }]
}

###
POST {{baseUrl}}/{{urlpath}}/users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "jammesdoe@example.com",
  "username": "janedoe123",
  "mobileNumber": "1234567890",
  "name": "James Dorren",
  "role": "Manager",
  "status": "active",
  "address": "123 Main Street, Springfield",
  "nin": "A24538394",
  "businessId": "675df7831e2e82150bc6c012"
}

###
GET  {{baseUrl}}/{{urlpath}}/users
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlpath}}/users/675df81e1e2e82150bc6c02d
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PATCH {{baseUrl}}/{{urlpath}}/users/675da5a7363965202058858c
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "name": "Jane Doe",
  "mobileNumber": "+1234567890",
  "status": "active",
  "languagePreference": "english",
  "emergencyContact": {
    "name": "Alice Doe",
    "relationship": "Sister",
    "contactNumber": "+9876543210"
  },
  "notificationPreferences": {
    "emailNotifications": false,
    "smsNotifications": true
  }
}

###
DELETE {{baseUrl}}/{{urlpath}}/users/675da60336396520205885a5
Content-Type: application/json
Accept: application/json
withCredentials: true