name: Build and deploy Node.js app to Azure Web App - marktbook
on:
    pull_request:
        branches: 
          - main
        types: [opened, synchronize]
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Changed to a more widely supported version
      - name: Cache dependencies for backend
        uses: actions/cache@v4
        with:
            path: marktbook-backend/node_modules
            key: ${{ runner.os }}-node-backend-${{ hashFiles('marktbook-backend/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-backend-
      - name: Install backend dependencies
        working-directory: marktbook-backend
        run: npm install
      - name: Run backend style check
        working-directory: marktbook-backend
        run: npm run lint

      # Create a proper deployment package
      - name: Prepare backend for deployment
        run: |
          mkdir -p deploy
          cp -r marktbook-backend/* deploy/
          cd deploy
          # Optional - remove test files and other non-production code
          rm -rf node_modules
          # Zip from the deploy directory
          cd ..
          zip -r release.zip deploy
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_53E681A629B341D39DED6DABAAFA29C1}}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F86B5B0A0DC44794902DA249D5E9738E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_93F5361ABCD745FF9FF3D9193BFE498D }}
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'marktbook'
          slot-name: 'Production'
          package: ./deploy  # Path to the extracted application files