name: CI test Pipeline

on:
  pull_request:
    branches: 
      - main
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: env 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies for backend
        uses: actions/cache@v3
        with:
          path: marktbook-backend/node_modules
          key: ${{ runner.os }}-node-backend-${{ hashFiles('marktbook-backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-backend-

      - name: Install backend dependencies
        working-directory: marktbook-backend
        run: npm install

      - name: Run backend style check
        working-directory: marktbook-backend
        run: npm run lint

      - name: Run backend tests
        continue-on-error: true
        working-directory: marktbook-backend
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test:ci

